swagger: '2.0'
info:
  version: '1.0'
  title: Kinbox Public API
  contact: {}
host: example.com
basePath: /integrations/chat
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /send:
    post:
      summary: Send
      tags:
      - Chat
      operationId: Send
      deprecated: false
      produces:
      - application/json; charset=utf-8
      parameters:
      - name: token
        in: query
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/SendRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Send'
          examples:
            application/json; charset=utf-8:
              queued: true
          headers:
            X-Powered-By:
              type: string
              default: Express
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            X-RateLimit-Limit:
              type: string
              default: '20'
            X-RateLimit-Remaining:
              type: string
              default: '19'
            Date:
              type: string
              default: Wed, 07 Jul 2021 23:30:19 GMT
            X-RateLimit-Reset:
              type: string
              default: '1625700667'
            Content-Length:
              type: string
              default: '15'
            ETag:
              type: string
              default: W/"f-iHWqDaYaObjmJUURGp5T7TD4nfM"
            Vary:
              type: string
              default: Accept-Encoding
            Connection:
              type: string
              default: keep-alive
definitions:
  SendRequest:
    title: SendRequest
    example:
      hidden: false
      message: mensagem de teste
      to: 558599253056@c.us
      channelId: 103
      callOptions:
        setGroupId: 10
        execAutoAttributionId: 8
    type: object
    properties:
      hidden:
        type: boolean
      message:
        type: string
      to:
        type: string
      channelId:
        type: integer
        format: int32
      callOptions:
        $ref: '#/definitions/CallOptions'
    required:
    - hidden
    - message
    - to
    - channelId
    - callOptions
  CallOptions:
    title: CallOptions
    example:
      setGroupId: 10
      execAutoAttributionId: 8
    type: object
    properties:
      setGroupId:
        type: integer
        format: int32
      execAutoAttributionId:
        type: integer
        format: int32
    required:
    - setGroupId
    - execAutoAttributionId
  Send:
    title: Send
    example:
      queued: true
    type: object
    properties:
      queued:
        type: boolean
    required:
    - queued
tags:
- name: Chat
